<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class RolesController extends Controller
{
    //

    // DEBE RETORNAR ALERTAS POR CADA GESTION QUE SE REALICE EN LA BASE DE DATOS.
    // DEBE RETORNAR ALERTAS POR CADA GESTION QUE SE REALICE EN LA BASE DE DATOS.
    // DEBE RETORNAR ALERTAS POR CADA GESTION QUE SE REALICE EN LA BASE DE DATOS.
    // DEBE RETORNAR ALERTAS POR CADA GESTION QUE SE REALICE EN LA BASE DE DATOS.
    // DEBE RETORNAR ALERTAS POR CADA GESTION QUE SE REALICE EN LA BASE DE DATOS.
    // DEBE RETORNAR ALERTAS POR CADA GESTION QUE SE REALICE EN LA BASE DE DATOS.
    // DEBE RETORNAR ALERTAS POR CADA GESTION QUE SE REALICE EN LA BASE DE DATOS.
    // DEBE RETORNAR ALERTAS POR CADA GESTION QUE SE REALICE EN LA BASE DE DATOS.
}
